In [4]:
import numpy as np

a = np.random.randint(0, 10, (20, 3))
b = np.random.randint(0, 10, (1, 3))

In [6]:
a

array([[9, 4, 4],
       [2, 5, 6],
       [7, 2, 7],
       [3, 4, 1],
       [9, 2, 4],
       [0, 4, 2],
       [0, 8, 8],
       [1, 2, 2],
       [6, 7, 5],
       [5, 0, 0],
       [3, 3, 1],
       [9, 9, 3],
       [3, 0, 8],
       [8, 5, 0],
       [1, 9, 4],
       [1, 2, 6],
       [5, 0, 5],
       [7, 6, 9],
       [4, 6, 1],
       [7, 8, 9]])

In [7]:
b

array([[9, 8, 4]])

In [5]:
a * b

array([[81, 32, 16],
       [18, 40, 24],
       [63, 16, 28],
       [27, 32,  4],
       [81, 16, 16],
       [ 0, 32,  8],
       [ 0, 64, 32],
       [ 9, 16,  8],
       [54, 56, 20],
       [45,  0,  0],
       [27, 24,  4],
       [81, 72, 12],
       [27,  0, 32],
       [72, 40,  0],
       [ 9, 72, 16],
       [ 9, 16, 24],
       [45,  0, 20],
       [63, 48, 36],
       [36, 48,  4],
       [63, 64, 36]])