In [11]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [12]:
# 当作为右值时，返回新数组
b = a[np.arange(4), [0, 1, 2, 0]]
b += 1
print(b)
print(a)
# 当作为左值时，返回视图
a[np.arange(4), [0, 1, 2, 0]] += 233
print(a)

[ 2  6 10 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[234   2   3]
 [  4 238   6]
 [  7   8 242]
 [243  11  12]]
