In [7]:
import torch

data = [[1, 2], [-1, -2]]
tensor = torch.FloatTensor(data)
print(torch.mm(tensor, tensor)) # 张量点积
d_tensor = tensor.flatten()
d_tensor.dot(d_tensor) # 两个一维张量点积

tensor([[-1., -2.],
        [ 1.,  2.]])


tensor(10.)

### Variable

In [21]:
from torch.autograd import Variable

tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True) # 已经deprecated，现在Tensor自身就支持自动梯度

t_out = torch.mean(tensor * tensor)
v_out = torch.mean(variable * variable) # 现在variable返回的也是tensor类型数据
print(t_out)
print(v_out)
print(type(variable))

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)
<class 'torch.Tensor'>


In [20]:
var = torch.randn((5, 10), requires_grad=True)
v_out = torch.mm(var.T, var).sum()
v_out.backward()
print(var.grad)
print(var.data)


tensor([[ 1.9602,  1.9602,  1.9602,  1.9602,  1.9602,  1.9602,  1.9602,  1.9602,
          1.9602,  1.9602],
        [-8.1849, -8.1849, -8.1849, -8.1849, -8.1849, -8.1849, -8.1849, -8.1849,
         -8.1849, -8.1849],
        [ 2.6186,  2.6186,  2.6186,  2.6186,  2.6186,  2.6186,  2.6186,  2.6186,
          2.6186,  2.6186],
        [-1.4872, -1.4872, -1.4872, -1.4872, -1.4872, -1.4872, -1.4872, -1.4872,
         -1.4872, -1.4872],
        [-5.3484, -5.3484, -5.3484, -5.3484, -5.3484, -5.3484, -5.3484, -5.3484,
         -5.3484, -5.3484]])
tensor([[ 0.9440, -0.5659, -0.3620,  0.3299,  1.3389,  0.1031,  1.8082, -1.3026,
         -0.2379, -1.0756],
        [-0.3402,  0.2823, -0.8741, -0.1557,  0.2063, -0.3083, -2.0371,  0.8854,
         -1.1348, -0.6162],
        [-0.6652,  0.8595, -0.6846, -1.0034,  0.8096,  0.2644,  1.7037,  0.5956,
         -0.0473, -0.5229],
        [-1.7504,  0.6869,  0.2387,  1.1984,  0.4815, -0.7954,  0.7671,  0.0163,
          0.2740, -1.8607],
        [-0.3678, 