In [29]:
import numpy as np
X = np.array([[-1, -1],
              [-2, -1],
              [-3, -2],
              [1, 1], 
              [2, 1],
              [3, 2]])
y = np.array([1, 1, 1, 2, 2, 2])

### Gaussian先验分布

In [6]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, y)
print("==== Predict result by predict function ====")
print(clf.predict([[-0.8, -1]]))
print("\n==== Predict result by predict_proba function ====")
print(clf.predict_proba([[-0.8, -1]]))
print("\n==== Predict result by predict_log_proba function ====")
print(clf.predict_log_proba([[-0.8, -1]]))

==== Predict result by predict function ====
[1]

==== Predict result by predict_proba function ====
[[9.99999949e-01 5.05653254e-08]]

==== Predict result by predict_log_proba function ====
[[-5.05653266e-08 -1.67999998e+01]]


### Multimonial先验分布

In [40]:
from sklearn.naive_bayes import MultinomialNB
# Multinomial不支持负数
X = np.array([[1, 1],
              [2, 1],
              [3, 2],
              [1, 1], 
              [2, 1],
              [3, 2]])
y = np.array([1, 1, 2, 2, 2, 2])
# clf = MultinomialNB(fit_prior=False, class_prior=[0.8, 0.2])
clf = MultinomialNB(fit_prior=True)
clf.fit(X, y)
print("==== Predict result by predict function ====")
print(clf.predict([[0.8, 1]]))
print("\n==== Predict result by predict_proba function ====")
print(clf.predict_proba([[0.8, 1]]))
print("\n==== Predict result by predict_log_proba function ====")
print(clf.predict_log_proba([[0.8, 1]]))

==== Predict result by predict function ====
[2]

==== Predict result by predict_proba function ====
[[0.33708048 0.66291952]]

==== Predict result by predict_log_proba function ====
[[-1.08743356 -0.41110169]]


### Bernoulli先验分布

In [36]:
from sklearn.naive_bayes import BernoulliNB

clf = BernoulliNB(fit_prior=True, binarize=0)
clf.fit(X, y)
print("==== Predict result by predict function ====")
print(clf.predict([[0.8, 1]]))
print("\n==== Predict result by predict_proba function ====")
print(clf.predict_proba([[0.8, 1]]))
print("\n==== Predict result by predict_log_proba function ====")
print(clf.predict_log_proba([[0.8, 1]]))

==== Predict result by predict function ====
[2]

==== Predict result by predict_proba function ====
[[0.05882353 0.94117647]]

==== Predict result by predict_log_proba function ====
[[-2.83321334 -0.06062462]]
